quarkus:
 datasource:
  db-kind: postgresql
  jdbc:
   url: "jdbc:postgresql://free-tier5.gcp-europe-west1.cockroachlabs.cloud:26257/defaultdb?options=--cluster%3Delite-chum-4479"
  username: dummy
  password: 7jQu7wq-gpLibqhfZySJxg
  reactive:
   postgresql:
    ssl-mode: require
 hibernate-orm:
  database:
   generation: update

